[build]
command = "./scripts/prepare-static.sh"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://api.example.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/p/*"
to = "/viewer.html"
status = 200

[[redirects]]
from = "/news"
to = "/news.html"
status = 200

[[redirects]]
from = "/about"
to = "/about.html"
status = 200
